/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as FamiliasIndexRouteImport } from './routes/familias.index'
import { Route as FamiliasIdIndexRouteImport } from './routes/familias.$id.index'
import { Route as FamiliasIdProtocoloRouteImport } from './routes/familias.$id.protocolo'
import { Route as FamiliasIdVisitaRouteImport } from './routes/familias.$id.visita'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliasIndexRoute = FamiliasIndexRouteImport.update({
  id: '/familias/',
  path: '/familias/',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliasIdIndexRoute = FamiliasIdIndexRouteImport.update({
  id: '/familias/$id/',
  path: '/familias/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliasIdProtocoloRoute = FamiliasIdProtocoloRouteImport.update({
  id: '/familias/$id/protocolo',
  path: '/familias/$id/protocolo',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliasIdVisitaRoute = FamiliasIdVisitaRouteImport.update({
  id: '/familias/$id/visita',
  path: '/familias/$id/visita',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/design-system': typeof DesignSystemRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/familias/': typeof FamiliasIndexRoute
  '/familias/$id/protocolo': typeof FamiliasIdProtocoloRoute
  '/familias/$id/visita': typeof FamiliasIdVisitaRoute
  '/familias/$id/': typeof FamiliasIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/design-system': typeof DesignSystemRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/familias': typeof FamiliasIndexRoute
  '/familias/$id/protocolo': typeof FamiliasIdProtocoloRoute
  '/familias/$id/visita': typeof FamiliasIdVisitaRoute
  '/familias/$id': typeof FamiliasIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/design-system': typeof DesignSystemRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/familias/': typeof FamiliasIndexRoute
  '/familias/$id/protocolo': typeof FamiliasIdProtocoloRoute
  '/familias/$id/visita': typeof FamiliasIdVisitaRoute
  '/familias/$id/': typeof FamiliasIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/design-system'
    | '/login'
    | '/onboarding'
    | '/perfil'
    | '/familias/'
    | '/familias/$id/protocolo'
    | '/familias/$id/visita'
    | '/familias/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/design-system'
    | '/login'
    | '/onboarding'
    | '/perfil'
    | '/familias'
    | '/familias/$id/protocolo'
    | '/familias/$id/visita'
    | '/familias/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/design-system'
    | '/login'
    | '/onboarding'
    | '/perfil'
    | '/familias/'
    | '/familias/$id/protocolo'
    | '/familias/$id/visita'
    | '/familias/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DesignSystemRoute: typeof DesignSystemRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PerfilRoute: typeof PerfilRoute
  FamiliasIndexRoute: typeof FamiliasIndexRoute
  FamiliasIdProtocoloRoute: typeof FamiliasIdProtocoloRoute
  FamiliasIdVisitaRoute: typeof FamiliasIdVisitaRoute
  FamiliasIdIndexRoute: typeof FamiliasIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/familias/': {
      id: '/familias/'
      path: '/familias'
      fullPath: '/familias/'
      preLoaderRoute: typeof FamiliasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/familias/$id/': {
      id: '/familias/$id/'
      path: '/familias/$id'
      fullPath: '/familias/$id/'
      preLoaderRoute: typeof FamiliasIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/familias/$id/protocolo': {
      id: '/familias/$id/protocolo'
      path: '/familias/$id/protocolo'
      fullPath: '/familias/$id/protocolo'
      preLoaderRoute: typeof FamiliasIdProtocoloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/familias/$id/visita': {
      id: '/familias/$id/visita'
      path: '/familias/$id/visita'
      fullPath: '/familias/$id/visita'
      preLoaderRoute: typeof FamiliasIdVisitaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DesignSystemRoute: DesignSystemRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PerfilRoute: PerfilRoute,
  FamiliasIndexRoute: FamiliasIndexRoute,
  FamiliasIdProtocoloRoute: FamiliasIdProtocoloRoute,
  FamiliasIdVisitaRoute: FamiliasIdVisitaRoute,
  FamiliasIdIndexRoute: FamiliasIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
